services:
  web:
    image: caddy:2-alpine
    container_name: kinopiohub-web
    restart: unless-stopped
    ports:
      - "7800:7800"
      - "7801:7801"
    volumes:
      - ./conf:/etc/caddy:ro
      - ./dist:/srv:ro
      - /root/NATS/cert.pem:/certs/cert.pem:ro
      - /root/NATS/key.key:/certs/key.key:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
